use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum BridgeOperation {
    ProcessFetch,
    ProcessAttach,
    AnalysisSnapshotLoad,
    AnalysisOverlayLoad,
    SceneCatalogLoad,
    SceneObjectChildrenLoad,
    SceneObjectChildrenPageLoad,
    SceneObjectInspect,
    SceneObjectInspectHeader,
    SceneObjectInspectChildrenPage,
    SceneObjectInspectComponentsPage,
    SceneObjectCreateRoot,
    SceneObjectCreateChild,
    SceneObjectDuplicate,
    SceneObjectDelete,
    SceneObjectRename,
    SceneObjectSetTag,
    SceneObjectSetLayer,
    SceneObjectSetHideFlags,
    SceneObjectReparent,
    SceneObjectSetActive,
    SceneObjectSetTransform,
    SceneComponentSetBehaviourEnabled,
    SceneComponentCreate,
    SceneComponentDelete,
    SceneLoadByBuildIndex,
    RuntimeFieldRead,
    RuntimeFieldWrite,
    RuntimeMethodInvoke,
}

impl BridgeOperation {
    pub fn as_protocol_name(&self) -> &'static str {
        match self {
            Self::ProcessFetch => "process-fetch",
            Self::ProcessAttach => "process-attach",
            Self::AnalysisSnapshotLoad => "analysis-snapshot-load",
            Self::AnalysisOverlayLoad => "analysis-overlay-load",
            Self::SceneCatalogLoad => "scene-catalog-load",
            Self::SceneObjectChildrenLoad => "scene-object-children-load",
            Self::SceneObjectChildrenPageLoad => "scene-object-children-page-load",
            Self::SceneObjectInspect => "scene-object-inspect",
            Self::SceneObjectInspectHeader => "scene-object-inspect-header",
            Self::SceneObjectInspectChildrenPage => "scene-object-inspect-children-page",
            Self::SceneObjectInspectComponentsPage => "scene-object-inspect-components-page",
            Self::SceneObjectCreateRoot => "scene-object-create-root",
            Self::SceneObjectCreateChild => "scene-object-create-child",
            Self::SceneObjectDuplicate => "scene-object-duplicate",
            Self::SceneObjectDelete => "scene-object-delete",
            Self::SceneObjectRename => "scene-object-rename",
            Self::SceneObjectSetTag => "scene-object-set-tag",
            Self::SceneObjectSetLayer => "scene-object-set-layer",
            Self::SceneObjectSetHideFlags => "scene-object-set-hide-flags",
            Self::SceneObjectReparent => "scene-object-reparent",
            Self::SceneObjectSetActive => "scene-object-set-active",
            Self::SceneObjectSetTransform => "scene-object-set-transform",
            Self::SceneComponentSetBehaviourEnabled => "scene-component-set-behaviour-enabled",
            Self::SceneComponentCreate => "scene-component-create",
            Self::SceneComponentDelete => "scene-component-delete",
            Self::SceneLoadByBuildIndex => "scene-load-by-build-index",
            Self::RuntimeFieldRead => "runtime-field-read",
            Self::RuntimeFieldWrite => "runtime-field-write",
            Self::RuntimeMethodInvoke => "runtime-method-invoke",
        }
    }
}
